services:
  myjavaapp:
    build: .
    ports: 
      - "8080:8080"
    environment:
      POSTGRES_URL: jdbc:postges://postgres:5432:5432/petclinic
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: petclinic
      POSTGRES_USER: petclinic
      POSTGRES_PASS: petclinic
      SPRING_PROFILES_ACTIVE: postgress
    depends_on:
        - postgres
    command: mvn clean package-DskipTests
      
  

  postgres:
    image: postgres:17.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
